config/routes.rb
Uncledolan::Application.routes.draw do
  get "library/index"

  resources :shops

  devise_for :users
  devise_scope :user do
    get 'logout', :to => "devise/sessions#destroy"
  end

  resources :products
  resources :payment_notifications
  root :to => "products#index"
  match 'shop_create' => "shops#create"
  match 'paypal' => "shops#express"
  get 'discount/adddiscount'
  match 'library' => "library#index"

end

app/models/shop.rb
class Shop < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
  
  def percentprice(num)
    percent = (num * 20) / 100
    return num - percent.to_i
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :verify_invoice
  # GET /shops
  # GET /shops.json

  def express
    shops = Shop.where(:user_id => current_user.id)
    invoice = Invoice.find_by_user_id_and_used(current_user.id, false).id
    values = {
      :business => 'fernan_1338285827_biz@gmail.com',
      :cmd => '_cart',
      :upload => 1,
      :return => 'http://uncledolan.inf.utfsm.cl/payment_notifications',
      :invoice => invoice,
      #:notify_url => 'http://uncledolan.inf.utfsm.cl/payment_notifications'
    }
    shops.each_with_index do |shop, index|
      if shop.product.discounts.find_by_user_id(current_user.id) != nil
      values.merge!({      
        "amount_#{index+1}" => to_dolar(percentprice(shop.product.Precio)),
        "item_name_#{index+1}" => shop.product.Nombre,
        "item_number_#{index+1}" => shop.product.Codigo,
        "quantity_#{index+1}" => 1
      })
      else
      values.merge!({      
        "amount_#{index+1}" => to_dolar(shop.product.Precio),
        "item_name_#{index+1}" => shop.product.Nombre,
        "item_number_#{index+1}" => shop.product.Codigo,
        "quantity_#{index+1}" => 1
      })
      end
    end
     
    # This is a paypal sandbox url and should be changed for production.
    # Better define this url in the application configuration setting on environment
    # basis.
    redirect_to("https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query)
  end

  def index
    @shops = Shop.where(:user_id => current_user.id)
    @histories = History.where(:user_id => current_user.id)
    @invoices = Invoice.where(:user_id => current_user.id, :used => true)
    @discounts = Discount.where(:user_id => current_user.id)
    
    @total = 0
    @shops.each do |shop|
      if shop.product.discounts.find_by_user_id(current_user.id) != nil
        @total += percentprice(shop.product.Precio)
      else
        @total += shop.product.Precio
      end
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shops }
    end
  end

  # GET /shops/1
  # GET /shops/1.json
#  def show
#    @shop = Shop.find(params[:id])

#    respond_to do |format|
#      format.html # show.html.erb
#      format.json { render json: @shop }
#    end
#  end
#
#  # GET /shops/new
#  # GET /shops/new.json
#  def new
#    @shop = Shop.new
#
#    respond_to do |format|
#      format.html # new.html.erb
#      format.json { render json: @shop }
#    end
#  end
#
#  # GET /shops/1/edit
#  def edit
#    @shop = Shop.find(params[:id])
#  end
#
#  # POST /shops
#  # POST /shops.json
  def create
    invoice = Invoice.find_by_user_id_and_used(current_user.id, false)
    @shop = Shop.new(:user_id => params[:user_id], :product_id => params[:product_id], :invoice_id => invoice.id)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to shops_path, notice: 'Shop was successfully created.' }
        format.json { render json: @shop, status: :created, location: @shop }
#      else
#        format.html { render action: "new" }
#        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end
#
#  # PUT /shops/1
#  # PUT /shops/1.json
#  def update
#    @shop = Shop.find(params[:id])
#
#    respond_to do |format|
#      if @shop.update_attributes(params[:shop])
#        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
#        format.json { head :no_content }
#      else
#        format.html { render action: "edit" }
#        format.json { render json: @shop.errors, status: :unprocessable_entity }
#      end
#    end
#  end
#
#  # DELETE /shops/1
#  # DELETE /shops/1.json
  def destroy
    @shop = Shop.find(params[:id])
    @shop.destroy

    respond_to do |format|
      format.html { redirect_to shops_url }
      format.json { head :no_content }
    end
  end
  
  def to_dolar(num)
    return num = ("%.2f" % (num/510.25)).to_f
  end

  def verify_invoice
    if Invoice.find_by_user_id_and_used(current_user.id, false) == nil
      Invoice.create(:user_id => current_user.id, :used => false)
    end
  end

  def percentprice(num)
    percent = (num * 20) / 100
    return num - percent.to_i
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.erb
<%= form_for(@shop) do |f| %>
  <% if @shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
      <% @shop.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.number_field :product_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shops/edit.html.erb
<h1>Editing shop</h1>

<%= render 'form' %>

<%= link_to 'Show', @shop %> |
<%= link_to 'Back', shops_path %>

app/views/shops/index.html.erb
<div class="page-header"><h1>Carro de Compra</h1></div>
<% if @shops != [] %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Código</th>
      <th>Nombre</th>
      <th>Descuento</th>
      <th>Precio</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @shops.each do |shop| -%>
    <tr>
      <td><%= shop.product.Codigo %></td>
      <td><%= shop.product.Nombre %></td>
      <% if Discount.find_by_user_id_and_product_id(current_user.id, shop.product.ID) != nil %>
      <td>20%</td>
      <% else %>
      <td>-</td>
      <% end %>
      <% if shop.product.discounts.find_by_user_id(current_user.id) == nil %>
      <td>$<%= shop.product.Precio %></td>
      <% else %>
      <td>$<%= shop.percentprice(shop.product.Precio) %></td>
      <% end %>
      <td><%= link_to 'Quitar', shop, :confirm => "¿Estás seguro que quieres eliminar este producto de tu carro de compras?", :method => :delete, :class => 'btn btn-mini btn-danger' %></td>
    </tr>
    <% end -%>
    <tr>
      <td></td>
      <td><b>Total</b></td>
      <td></td>
      <td><b>$<%= @total %></b></td>
      <td></td>
    </tr>
  </tbody>
</table>
<div class="pull-right">
  <%= link_to image_tag("https://www.paypal.com/en_US/i/btn/btn_xpressCheckout.gif"), paypal_path %>
</div>
<% else %>
<div>
Tu carro de compras está vacío
</div>
<% end %>

<br /><br /><br /><br />
<br /><br /><br /><br />
<br /><br /><br /><br />
<div class="page-header"><h1>Historial de Compra</h1></div>
<% if @histories != [] %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Invoice</th>
      <th>Código</th>
      <th>Nombre</th>
      <th>Precio</th>
      <th>Fecha de Compra</th>
    </tr>
  </thead>
  <% @invoices.each do |invoice| -%>
  <tbody>
    <% invoice.histories.each do |history| %>
    <tr>
      <td><%= invoice.id %></td>
      <td><%= history.product_cod %></td>
      <td><%= history.product_name %></td>
      <td>$<%= history.product_price %></td>
      <td><%= history.created_at %></td>
    </tr>
    <% end %>
  </tbody>
  <% end -%>
</table>
<% else %>
<div>
Hasta ahora no ha realizado ninguna compra.
</div>
<% end %>

app/views/shops/new.html.erb
<h1>New shop</h1>

<%= render 'form' %>

<%= link_to 'Back', shops_path %>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @shop.user_id %>
</p>

<p>
  <b>Product:</b>
  <%= @shop.product_id %>
</p>


<%= link_to 'Edit', edit_shop_path(@shop) %> |
<%= link_to 'Back', shops_path %>