config/routes.rb
Uncledolan::Application.routes.draw do
  get "library/index"

  resources :shops

  devise_for :users
  devise_scope :user do
    get 'logout', :to => "devise/sessions#destroy"
  end

  resources :products
  resources :payment_notifications
  root :to => "products#index"
  match 'shop_create' => "shops#create"
  match 'paypal' => "shops#express"
  get 'discount/adddiscount'
  match 'library' => "library#index"

end

app/models/payment_notification.rb
class PaymentNotification < ActiveRecord::Base
  belongs_to :shop
  serialize :params
  #after_create :mark_shop_as_purchased

  #private

  #def mark_shop_as_purchased
  #  if status == "Completed"
  #    shop.update_attribute(:purchased_at, Time.now)
  #  end
  #end
end

app/controllers/payment_notifications_controller.rb
class PaymentNotificationsController < ApplicationController
  protect_from_forgery :except => [:create]
  # GET /payment_notifications
  # GET /payment_notifications.json
  # POST /payment_notifications
  # POST /payment_notifications.json
  def create
    parametros = 0
    if params[:st] == "Completed"
      parametros = Hash.from_xml(RestClient.get('https://www.sandbox.paypal.com/cgi-bin/webscr', :cmd => '_notify-synch', :tx => params[:tx], :at => 'XKFKHGKGTPXV6'))
    end
    #PaymentNotification.create(:params => params, :shop_id => params[:invoice], :status => params[:payment_status], :transaction_id => params[:txn_id])
    #if parametros[:payment_status] == "Completed"
    #  invoice = Invoice.find(parametros[:invoice])
    #  invoice.used = true
    #  user_id = invoice.user_id

    #  items = Shop.where(:invoice_id => invoice.id)
  
    #  items.each do |item|
    #    history = History.new
    #    history.user_id = user_id
    #    history.product_name = item.product.Nombre
    #    history.product_price = item.product.Precio
    #    history.product_cod = item.product.Codigo
    #    history.invoice_id = invoice.id
    #    history.save
    #  end
  
    #  invoice.save
    #  items.destroy_all
    #end
    redirect_to shops_path
  end

#  def index
#    @payment_notifications = PaymentNotification.all
#
#    respond_to do |format|
#      format.html # index.html.erb
#      format.json { render json: @payment_notifications }
#    end
#  end
#
#  # GET /payment_notifications/1
#  # GET /payment_notifications/1.json
#  def show
#    @payment_notification = PaymentNotification.find(params[:id])
#
#    respond_to do |format|
#      format.html # show.html.erb
#      format.json { render json: @payment_notification }
#    end
#  end
#
#  # GET /payment_notifications/new
#  # GET /payment_notifications/new.json
#  def new
#    @payment_notification = PaymentNotification.new
#
#    respond_to do |format|
#      format.html # new.html.erb
#      format.json { render json: @payment_notification }
#    end
#  end
#
#  # GET /payment_notifications/1/edit
#  def edit
#    @payment_notification = PaymentNotification.find(params[:id])
#  end
#
#  
#
#  # PUT /payment_notifications/1
#  # PUT /payment_notifications/1.json
#  def update
#    @payment_notification = PaymentNotification.find(params[:id])
#
#    respond_to do |format|
#      if @payment_notification.update_attributes(params[:payment_notification])
#        format.html { redirect_to @payment_notification, notice: 'Payment notification was successfully updated.' }
#        format.json { head :no_content }
#      else
#        format.html { render action: "edit" }
#        format.json { render json: @payment_notification.errors, status: :unprocessable_entity }
#      end
#    end
#  end
#
#  # DELETE /payment_notifications/1
#  # DELETE /payment_notifications/1.json
#  def destroy
#    @payment_notification = PaymentNotification.find(params[:id])
#    @payment_notification.destroy
#
#    respond_to do |format|
#      format.html { redirect_to payment_notifications_url }
#      format.json { head :no_content }
#    end
#  end
end

app/helpers/payment_notifications_helper.rb
module PaymentNotificationsHelper
end

app/views/payment_notifications/_form.html.erb
<%= form_for(@payment_notification) do |f| %>
  <% if @payment_notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment_notification.errors.count, "error") %> prohibited this payment_notification from being saved:</h2>

      <ul>
      <% @payment_notification.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :params %><br />
    <%= f.text_area :params %>
  </div>
  <div class="field">
    <%= f.label :shop_id %><br />
    <%= f.number_field :shop_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :transaction_id %><br />
    <%= f.text_field :transaction_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payment_notifications/edit.html.erb
<h1>Editing payment_notification</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment_notification %> |
<%= link_to 'Back', payment_notifications_path %>

app/views/payment_notifications/index.html.erb
<h1>Listing payment_notifications</h1>

<table>
  <tr>
    <th>Params</th>
    <th>Shop</th>
    <th>Status</th>
    <th>Transaction</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @payment_notifications.each do |payment_notification| %>
  <tr>
    <td><%= payment_notification.params %></td>
    <td><%= payment_notification.shop_id %></td>
    <td><%= payment_notification.status %></td>
    <td><%= payment_notification.transaction_id %></td>
    <td><%= link_to 'Show', payment_notification %></td>
    <td><%= link_to 'Edit', edit_payment_notification_path(payment_notification) %></td>
    <td><%= link_to 'Destroy', payment_notification, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Payment notification', new_payment_notification_path %>

app/views/payment_notifications/new.html.erb
<h1>New payment_notification</h1>

<%= render 'form' %>

<%= link_to 'Back', payment_notifications_path %>

app/views/payment_notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Params:</b>
  <%= @payment_notification.params %>
</p>

<p>
  <b>Shop:</b>
  <%= @payment_notification.shop_id %>
</p>

<p>
  <b>Status:</b>
  <%= @payment_notification.status %>
</p>

<p>
  <b>Transaction:</b>
  <%= @payment_notification.transaction_id %>
</p>


<%= link_to 'Edit', edit_payment_notification_path(@payment_notification) %> |
<%= link_to 'Back', payment_notifications_path %>