config/routes.rb
Uncledolan::Application.routes.draw do
  get "library/index"

  resources :shops

  devise_for :users
  devise_scope :user do
    get 'logout', :to => "devise/sessions#destroy"
  end

  resources :products
  resources :payment_notifications
  root :to => "products#index"
  match 'shop_create' => "shops#create"
  match 'paypal' => "shops#express"
  get 'discount/adddiscount'
  match 'library' => "library#index"

end

app/models/product.rb
class Product < ActiveRecord::Base
  establish_connection(:external_product_db)
  set_table_name 'Productos'
  has_many :shops
  has_many :users, :through => :shops
  has_many :discounts
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.paginate(:page => params[:page], :per_page => 8)
  end

  def show
    @product = Product.find(params[:id])
    @shop = Shop.new
  end
end

app/views/products/_form.html.erb
<%= form_for @product, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :ID, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :ID, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :Codigo, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :Codigo, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :Nombre, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :Nombre, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :Descripcion, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :Descripcion, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :Plataforma, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :Plataforma, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :Precio, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :Precio, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :Img, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :Img, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                products_path, :class => 'btn' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<%- model_class = @product.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/index.html.erb
<div class="page-header">
  <h1>Productos</h2>
</div>
<%= will_paginate @products, :renderer => BootstrapPagination::Rails %>
<ul class="thumbnails">
  <% @products.each do |product| -%>
  <li class="span4">
    <div class="thumbnail">
      <a href=<%= product_path(product) %> class="thumbnail">
        <img src="data:image/jpeg;base64,<%= product.Img %>" alt="">
      </a>
      <div class="caption">
        <h4>
        <%= link_to product.Nombre, product %>
        <% if product.Plataforma == "PC" %>
          <span class="label label-inverse">PC</span>
        <% else %>
          <span class="label label-info">PS3</span>
        <% end %></h4>
        <p>Precio: $<%= product.Precio %></p>
      </div>
    </div>
  </li>
  <% end -%>
</ul>
<%= will_paginate @products, :renderer => BootstrapPagination::Rails %>

app/views/products/new.html.erb
<%- model_class = @product.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/show.html.erb
<div id="fb-root"></div>
<script src='http://connect.facebook.net/en_US/all.js'></script>

<script> 
      FB.init({appId: "299578110137980", status: true, cookie: true});

      function postToFeed() {

        // calling the API ...
        var obj = {
          method: 'feed',
          message: 'He comprado un videojuego en UncleDolan Gaming Shop!',
          name: 'UncleDolan Gaming Shop',
          caption: 'He comprado un video juego en UncleDolan Gaming Shop!',
          description: (
           'UncleDolan es una tienda online de video juegos  ' +
           'en el que podrás encontrar las mejores ofertas. ' +
           'Compra pls.'
          ),
          link: 'http://uncledolan.inf.utfsm.cl',
          picture: 'http://distilleryimage1.instagram.com/7186c71692aa11e1ab011231381052c0_7.jpg'
        };

        function callback(response) {
          //document.getElementById('msg').innerHTML = "Post ID: " + response['post_id'];
         if (response && response.post_id) {
           var id = <%= current_user.id %>;
           var product = <%= @product.ID %>;
           var dir = 'http://uncledolan.inf.utfsm.cl/discount/adddiscount/?user='+id+'&product='+product;
           window.location = dir;
         } else{
           alert('El descuento no se ha obtenido!');
         };
        }

        FB.ui(obj, callback);
      }
    
</script>


<div class="page-header">
  <h1><%= @product.Nombre %></h1>
</div>

<div class="row">
  <div class="span4">
    <img src="data:image/jpeg;base64,<%= @product.Img %>" alt=""><br /><br />
    <p><span class="label label-info">¡Descuento!</span> <b>Si compartes este producto en tu Facebook, obtendrás un ¡20% de descuento!</b></p>
    <p>Compartir:</p>
    <p><%= link_to image_tag("facebook.jpg", :size => "40x40"), '#', :onclick => 'postToFeed(); return false;' %></p>
  </div>
  <div class="span4">
    <table class="table">
      <tbody>
        <tr>
          <th>Código:</th>
          <td><%= @product.Codigo %></td>
        </tr>
        <tr>
          <th>Nombre:</th>
          <td><%= @product.Nombre %></td>
        </tr>
        <tr>
          <th>Plataforma:</th>
          <td><%= @product.Plataforma %></td>
        </tr>
        <tr>
          <th>Descripción:</th>
          <td><%= @product.Descripcion %></td>
        </tr>
        <tr>
          <th>Precio:</th>
          <td>$<%= @product.Precio %></td>
        </tr>
      </tbody>
    </table>
    <%= link_to raw('<i class="icon-shopping-cart icon-white"></i> Añadir al carro'), { :controller => 'shops', :action => 'create', :user_id => current_user.id, :product_id => @product.ID }, :class => 'btn btn-success pull-right', :method => :post %>
  </div>
</div>