config/routes.rb
Uncledolan::Application.routes.draw do
  get "library/index"

  resources :shops

  devise_for :users
  devise_scope :user do
    get 'logout', :to => "devise/sessions#destroy"
  end

  resources :products
  resources :payment_notifications
  root :to => "products#index"
  match 'shop_create' => "shops#create"
  match 'paypal' => "shops#express"
  get 'discount/adddiscount'
  match 'library' => "library#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Uncledolan" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "jquery", "jquery_ujs", "twitter/bootstrap", "bootstrap-dropdown" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href=<%= root_path %>>Uncledolan Gaming Shop</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">MI CUENTA<b class="caret"></b></a>
                <ul class="dropdown-menu">
                <% if user_signed_in? %>
                  <li><%= link_to 'Editar Cuenta', root_path %></li>
                  <li><%= link_to 'Salir', logout_path %></li>
                <% else %>
                  <li><%= link_to 'Identificarse', new_user_session_path %></li>
                  <li><%= link_to 'Registrarse', new_user_registration_path %></li>
                <% end %>
                </ul>
              <li><%= link_to 'MI CARRO', shops_path  %></li>
              <% if user_signed_in= %>
              <li><%= link_to 'BIBLIOTECA', library_path  %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

     <div class="container">
       <div class="content">
         <div class="row">
            <div class="span8">
               <%= yield %>
             </div>
             <div class="span4">
               <div class="well sidebar-nav">
                 <h3>Bienvenido!</h3>
                 <ul class="nav nav-list">
                   <li class="nav-header">Bienvenido a UncleDolan Gaming Shop</li>
		   <p>Te damos la bienvenida a nuestro sitio en donde podrás comprar los mejores juegos de este último tiempo. Además, tenemos grandes ofertas! COMPRA OR DIE</p>
                   <!--<li><%#= link_to "MI CUENTA",   %></li>-->
                 </ul>
               </div><!--/.well -->
             </div><!--/span-->
         </div><!--/row-->
       </div><!--/content-->


 
       <footer>
         <p>&copy; Company 2012</p>
       </footer>
 
     </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
  </body>
</html>